### ISSUE TITLE
How to get picks and bans of a private game?

### ISSUE THREAD

**Issue by ACmagic** [Nuqlear/genkstaleague#2]
Can you please advise how to get picks and bans?

![image](https://user-images.githubusercontent.com/6644559/56862641-a0541800-69df-11e9-9968-15409095dca3.png)

**Comment by Nuqlear** [comment]
I have just tested dem2json on a recent replay and it returned correct picks and bans.
Maybe your game was not played in the captains mode? Because its not working for other modes (even for CD).
